# Generated by Django 2.0.5 on 2022-05-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=100)),
                ('event_image', models.ImageField(default='abc.jpg', upload_to='images')),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('start_Time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mobile', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.Category')),
            ],
            options={
                'db_table': 'event_list',
            },
        ),
    ]
