# Generated by Django 2.0.5 on 2022-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
