# Generated by Django 2.0.5 on 2022-05-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_auto_20220529_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='ticket_amount',
            field=models.IntegerField(default=200),
        ),
    ]
