# Generated by Django 2.0.5 on 2022-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_eventlist_ticket_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='ticket_amount',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
