# Generated by Django 2.0.5 on 2022-05-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_auto_20220529_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlist',
            old_name='tickt_amount',
            new_name='ticekt_amount',
        ),
    ]
