# Generated by Django 2.0.5 on 2022-05-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
