# Generated by Django 2.0.5 on 2022-05-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_auto_20220529_1223'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.EventList')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.UserDetails')),
            ],
            options={
                'db_table': 'BookEvent',
            },
        ),
    ]
